# Generated by Django 5.1.4 on 2026-02-10 04:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='online', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('rated_power_w', models.FloatField(help_text='Rated power consumption in watts', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('min_power_w', models.FloatField(help_text='Minimum power consumption in watts', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('max_power_w', models.FloatField(help_text='Maximum power consumption in watts', validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Air Conditioner',
                'verbose_name_plural': 'Air Conditioners',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('capacity_kwh', models.FloatField(help_text='Total battery capacity in kWh', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('current_charge_kwh', models.FloatField(default=0.0, help_text='Current charge level in kWh', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_charge_rate_kw', models.FloatField(help_text='Maximum charging rate in kW', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('max_discharge_rate_kw', models.FloatField(help_text='Maximum discharging rate in kW', validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': 'Battery',
                'verbose_name_plural': 'Batteries',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='ElectricVehicle',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('capacity_kwh', models.FloatField(help_text='Total battery capacity in kWh', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('current_charge_kwh', models.FloatField(default=0.0, help_text='Current charge level in kWh', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_charge_rate_kw', models.FloatField(help_text='Maximum charging rate in kW', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('max_discharge_rate_kw', models.FloatField(help_text='Maximum discharging rate in kW (V2H)', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('mode', models.CharField(choices=[('charging', 'Charging'), ('discharging', 'Discharging'), ('offline', 'Offline (Driving)')], default='charging', help_text='Current operating mode', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time the EV was connected', null=True)),
                ('driving_efficiency_kwh_per_hour', models.FloatField(default=3.0, help_text='Energy consumption while driving (kWh/hour)', validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': 'Electric Vehicle',
                'verbose_name_plural': 'Electric Vehicles',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('rated_output_w', models.FloatField(help_text='Rated power output in watts', validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Generator',
                'verbose_name_plural': 'Generators',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='Heater',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('rated_power_w', models.FloatField(help_text='Rated power consumption in watts', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('min_power_w', models.FloatField(help_text='Minimum power consumption in watts', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('max_power_w', models.FloatField(help_text='Maximum power consumption in watts', validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Heater',
                'verbose_name_plural': 'Heaters',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('panel_area_m2', models.FloatField(help_text='Panel area in square meters', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('efficiency', models.FloatField(help_text='Panel efficiency (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('max_capacity_w', models.FloatField(help_text='Maximum power output in watts', validators=[django.core.validators.MinValueValidator(1.0)])),
                ('latitude', models.FloatField(default=37.77, help_text='Installation latitude (default: San Francisco)', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(default=-122.42, help_text='Installation longitude (default: San Francisco)', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
            ],
            options={
                'verbose_name': 'Solar Panel',
                'verbose_name_plural': 'Solar Panels',
            },
            bases=('devices.device',),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='devices_dev_user_id_2c8247_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['created_at'], name='devices_dev_created_f36e7e_idx'),
        ),
    ]
